# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('director', models.TextField()),
                ('country', models.TextField()),
                ('trailer', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('duration', models.TextField()),
                ('genre', models.TextField()),
                ('synopsis', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('director', models.TextField()),
                ('country', models.TextField()),
                ('trailer', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('duration', models.TextField()),
                ('season', models.IntegerField()),
                ('chapters', models.IntegerField()),
                ('genre', models.TextField()),
                ('synopsis', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('group', models.TextField()),
                ('album', models.TextField()),
                ('country', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.TextField()),
                ('song_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
